.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinnoomy_qt test_bitcoinnoomy_qt
clean: FORCE
	$(MAKE) -C .. bitcoinnoomy_qt_clean test_bitcoinnoomy_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinnoomy_qt_check
bitcoinnoomy-qt bitcoinnoomy-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinnoomy_qt
